[package]
name    = "aethos_cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cargo-aethos"
path = "src/main.rs"

[dependencies]
serde.workspace      = true
serde_json.workspace = true
tokio.workspace      = true
aethos_orm           = { path = "../aethos_orm" }
regex = "1"
sqlx = { version = "0.8", features = ["runtime-tokio-native-tls", "sqlite"] }
