//! `Schema` — trait for structs that map to a database table.
//!
//! Derive it with `#[derive(Schema)]` from `aethos_orm_macros`.
//!
//! # Example
//!
//! ```rust,ignore
//! use aethos_orm::Schema;
//! use sqlx::FromRow;
//!
//! #[derive(Debug, Schema, FromRow)]
//! #[schema(table = "users")]
//! pub struct User {
//!     #[field(primary_key)]
//!     pub id:    i64,
//!     pub name:  String,
//!     pub email: String,
//! }
//! ```

use crate::value::SqlValue;

/// Trait for structs that represent a database table row.
///
/// Derive via `#[derive(Schema)]` — the macro generates all four methods.
/// Manual implementation is also supported.
pub trait Schema {
    /// The database table name (e.g. `"users"`).
    fn table_name() -> &'static str;

    /// The primary key column name (default: `"id"`).
    fn primary_key() -> &'static str { "id" }

    /// Column names for INSERT operations (excludes the primary key).
    fn columns() -> &'static [&'static str];

    /// Produce a `SqlValue` per column in the same order as `columns()`.
    ///
    /// Generated by `#[derive(Schema)]`. Each field is converted via `From`
    /// — no JSON serialisation intermediate.
    fn to_row_values(&self) -> Vec<SqlValue>;

    /// The value of the primary key column for this row.
    ///
    /// Returns `SqlValue::Null` for structs with no `#[field(primary_key)]`.
    /// Used by `Repo::update` to build the `WHERE id = ?` clause.
    fn primary_key_value(&self) -> SqlValue { SqlValue::Null }
}
