//! `SqlValue` — a typed value that can be bound to any sqlx query parameter.
//!
//! Generated by `#[derive(Schema)]` via `to_row_values()` — replaces the
//! `serde_json::Value` intermediate that `insert_json` used previously.

/// A database-ready value produced by `Schema::to_row_values`.
///
/// Implements `From<T>` for all primitive types so that the generated
/// `to_row_values()` code can write `field.clone().into()` for any supported
/// column type.
#[derive(Debug, Clone)]
pub enum SqlValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
}

// ── From impls ────────────────────────────────────────────────────────────────

impl From<bool>    for SqlValue { fn from(v: bool)    -> Self { Self::Bool(v) } }
impl From<i8>      for SqlValue { fn from(v: i8)      -> Self { Self::Int(v as i64) } }
impl From<i16>     for SqlValue { fn from(v: i16)     -> Self { Self::Int(v as i64) } }
impl From<i32>     for SqlValue { fn from(v: i32)     -> Self { Self::Int(v as i64) } }
impl From<i64>     for SqlValue { fn from(v: i64)     -> Self { Self::Int(v) } }
impl From<u8>      for SqlValue { fn from(v: u8)      -> Self { Self::Int(v as i64) } }
impl From<u16>     for SqlValue { fn from(v: u16)     -> Self { Self::Int(v as i64) } }
impl From<u32>     for SqlValue { fn from(v: u32)     -> Self { Self::Int(v as i64) } }
impl From<f32>     for SqlValue { fn from(v: f32)     -> Self { Self::Float(v as f64) } }
impl From<f64>     for SqlValue { fn from(v: f64)     -> Self { Self::Float(v) } }
impl From<String>  for SqlValue { fn from(v: String)  -> Self { Self::Text(v) } }
impl From<Vec<u8>> for SqlValue { fn from(v: Vec<u8>) -> Self { Self::Bytes(v) } }

impl From<&str> for SqlValue {
    fn from(v: &str) -> Self { Self::Text(v.to_owned()) }
}

impl<T: Into<SqlValue>> From<Option<T>> for SqlValue {
    fn from(v: Option<T>) -> Self {
        match v {
            Some(t) => t.into(),
            None    => Self::Null,
        }
    }
}

// ── Database binding ──────────────────────────────────────────────────────────

impl SqlValue {
    /// Bind onto a SQLite query. Consumes `self` — no clone needed.
    pub fn bind_sqlite<'q>(
        self,
        q: sqlx::query::Query<'q, sqlx::Sqlite, sqlx::sqlite::SqliteArguments<'q>>,
    ) -> sqlx::query::Query<'q, sqlx::Sqlite, sqlx::sqlite::SqliteArguments<'q>> {
        match self {
            SqlValue::Null     => q.bind(None::<String>),
            SqlValue::Bool(b)  => q.bind(b),
            SqlValue::Int(i)   => q.bind(i),
            SqlValue::Float(f) => q.bind(f),
            SqlValue::Text(s)  => q.bind(s),
            SqlValue::Bytes(b) => q.bind(b),
        }
    }

    /// Bind onto a Postgres query. Consumes `self`.
    pub fn bind_postgres<'q>(
        self,
        q: sqlx::query::Query<'q, sqlx::Postgres, sqlx::postgres::PgArguments>,
    ) -> sqlx::query::Query<'q, sqlx::Postgres, sqlx::postgres::PgArguments> {
        match self {
            SqlValue::Null     => q.bind(None::<String>),
            SqlValue::Bool(b)  => q.bind(b),
            SqlValue::Int(i)   => q.bind(i),
            SqlValue::Float(f) => q.bind(f),
            SqlValue::Text(s)  => q.bind(s),
            SqlValue::Bytes(b) => q.bind(b),
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_primitives() {
        assert!(matches!(SqlValue::from(42i64),       SqlValue::Int(42)));
        assert!(matches!(SqlValue::from(3.14f64),     SqlValue::Float(_)));
        assert!(matches!(SqlValue::from(true),        SqlValue::Bool(true)));
        assert!(matches!(SqlValue::from("hi"),        SqlValue::Text(_)));
        assert!(matches!(SqlValue::from(None::<i64>), SqlValue::Null));
        assert!(matches!(SqlValue::from(Some(7i64)),  SqlValue::Int(7)));
    }
}
